"""Machine-readable CashTokens scenario catalog.

A vector is data. The generator is code. IDs are stable.
"""

from __future__ import annotations

from typing import Any

NFT = lambda cap, commit="": {"nft": {"capability": cap, "commitment": commit}, "amount": 0}
FT = lambda amt: {"nft": None, "amount": amt}
HYB = lambda cap, amt, commit="": {"nft": {"capability": cap, "commitment": commit}, "amount": amt}


def _e(
    id: str,
    group: str,
    title: str,
    description: str | None = None,
    *,
    expected_consensus: str = "valid",
    expected_psbt: str = "valid",
    invalid_code: str | None = None,
    existing: list | None = None,
    inputs: list | None = None,
    outputs: list | None = None,
    script_type: str = "p2pkh",
    sighash: str = "ALL|FORKID",
    dialects: list | None = None,
    sign_states: list | None = None,
    justification: str = "CHIP-2022-02-CashTokens v2.2.2 token validation algorithm",
    extra: dict | None = None,
) -> dict[str, Any]:
    d: dict[str, Any] = {
        "id": id,
        "group": group,
        "title": title,
        "description": description or title,
        "expected_consensus": expected_consensus,
        "expected_psbt": expected_psbt,
        "invalid_code": invalid_code,
        "existing": existing or [],
        "inputs": inputs or [],
        "outputs": outputs or [],
        "script_type": script_type,
        "sighash": sighash,
        "dialects": dialects or ["bip174-v0"],
        "sign_states": sign_states or ["unsigned"],
        "justification": justification,
    }
    if extra:
        d.update(extra)
    return d


def build_catalog() -> list[dict[str, Any]]:
    c: list[dict[str, Any]] = []

    # ── Genesis ──────────────────────────────────────────────────────────
    c += [
        _e("GEN-01", "genesis", "NFT immutable genesis",
           "Spend vout=0 BCH UTXO; create one immutable NFT of the new category.",
           inputs=[{"kind": "genesis_parent", "key": "A", "owner": "alice", "sats": 100000}],
           outputs=[{"owner": "bob", "sats": 98000, "genesis_from": 0, "token": NFT("none", "cafebabe")}],
           dialects=["bip174-v0", "paytaca-145"], sign_states=["unsigned", "signed"]),
        _e("GEN-02", "genesis", "NFT mutable genesis",
           "Genesis a single mutable NFT.",
           inputs=[{"kind": "genesis_parent", "key": "A", "owner": "alice", "sats": 100000}],
           outputs=[{"owner": "bob", "sats": 98000, "genesis_from": 0, "token": NFT("mutable", "01")}],
           dialects=["bip174-v0", "paytaca-145"], sign_states=["unsigned", "signed"]),
        _e("GEN-03", "genesis", "NFT minting genesis",
           "Genesis a minting baton (capability 2) with empty commitment.",
           inputs=[{"kind": "genesis_parent", "key": "A", "owner": "alice", "sats": 100000}],
           outputs=[{"owner": "alice", "sats": 98000, "genesis_from": 0, "token": NFT("minting", "")}],
           dialects=["bip174-v0", "paytaca-145"], sign_states=["unsigned", "signed"]),
        _e("GEN-04", "genesis", "FT genesis",
           "Genesis 1_000_000 fungible tokens, no NFT.",
           inputs=[{"kind": "genesis_parent", "key": "A", "owner": "alice", "sats": 100000}],
           outputs=[{"owner": "bob", "sats": 98000, "genesis_from": 0, "token": FT(1_000_000)}],
           dialects=["bip174-v0", "paytaca-145"], sign_states=["unsigned", "signed"]),
        _e("GEN-05", "genesis", "Hybrid NFT+FT genesis",
           "Same output carries minting NFT and FT of the new category.",
           inputs=[{"kind": "genesis_parent", "key": "A", "owner": "alice", "sats": 100000}],
           outputs=[{"owner": "alice", "sats": 98000, "genesis_from": 0, "token": HYB("minting", 5000, "")}],
           dialects=["bip174-v0", "paytaca-145"], sign_states=["unsigned", "signed"]),
        _e("GEN-06", "genesis", "Multiple NFT outputs at genesis",
           "One genesis input; three immutable NFTs with distinct commitments.",
           inputs=[{"kind": "genesis_parent", "key": "A", "owner": "alice", "sats": 200000}],
           outputs=[
               {"owner": "bob", "sats": 1000, "genesis_from": 0, "token": NFT("none", "aa")},
               {"owner": "carol", "sats": 1000, "genesis_from": 0, "token": NFT("none", "bb")},
               {"owner": "alice", "sats": 197000, "genesis_from": 0, "token": NFT("minting", "")},
           ],
           dialects=["bip174-v0", "paytaca-145"]),
        _e("GEN-07", "genesis", "Multiple FT outputs at genesis",
           "Split genesis FT supply across two outputs (100+50).",
           inputs=[{"kind": "genesis_parent", "key": "A", "owner": "alice", "sats": 100000}],
           outputs=[
               {"owner": "bob", "sats": 1000, "genesis_from": 0, "token": FT(100)},
               {"owner": "alice", "sats": 98000, "genesis_from": 0, "token": FT(50)},
           ]),
        _e("GEN-08", "genesis", "Two categories in one transaction",
           "Two genesis_parent inputs (each vout=0 of a different parent).",
           inputs=[
               {"kind": "genesis_parent", "key": "A", "owner": "alice", "sats": 50000},
               {"kind": "genesis_parent", "key": "B", "owner": "alice", "sats": 50000},
           ],
           outputs=[
               {"owner": "bob", "sats": 1000, "genesis_from": 0, "token": NFT("none", "01")},
               {"owner": "carol", "sats": 1000, "genesis_from": 1, "token": FT(999)},
               {"owner": "alice", "sats": 97000},
           ],
           dialects=["bip174-v0", "paytaca-145"]),
        _e("GEN-09", "genesis", "Genesis FT amount 1 (minimum)",
           "FT amount 1, CompactSize 0x01.",
           inputs=[{"kind": "genesis_parent", "key": "A", "owner": "alice", "sats": 10000}],
           outputs=[{"owner": "bob", "sats": 8000, "genesis_from": 0, "token": FT(1)}]),
        _e("GEN-10", "genesis", "Genesis FT amount 252 vs 253 CompactSize boundary",
           "252 uses 1-byte CompactSize; companion GEN-11 uses 253.",
           inputs=[{"kind": "genesis_parent", "key": "A", "owner": "alice", "sats": 10000}],
           outputs=[{"owner": "bob", "sats": 8000, "genesis_from": 0, "token": FT(252)}]),
        _e("GEN-11", "genesis", "Genesis FT amount 253 (0xfd encoding)",
           inputs=[{"kind": "genesis_parent", "key": "A", "owner": "alice", "sats": 10000}],
           outputs=[{"owner": "bob", "sats": 8000, "genesis_from": 0, "token": FT(253)}]),
        _e("GEN-12", "genesis", "Empty-commitment immutable NFT genesis",
           "Bitfield 0x20, no HAS_COMMITMENT_LENGTH.",
           inputs=[{"kind": "genesis_parent", "key": "A", "owner": "alice", "sats": 10000}],
           outputs=[{"owner": "bob", "sats": 8000, "genesis_from": 0, "token": NFT("none", "")}]),
        _e("GEN-13", "genesis", "40-byte commitment (consensus max Upgrade 9)",
           inputs=[{"kind": "genesis_parent", "key": "A", "owner": "alice", "sats": 10000}],
           outputs=[{"owner": "bob", "sats": 8000, "genesis_from": 0,
                     "token": NFT("none", "cc" * 40)}]),
        _e("GEN-14", "genesis", "Genesis input is tx input index 1 (vout still 0)",
           "Distinguishes vin index from prevout.n. First input is BCH vout=1; second is genesis.",
           inputs=[
               {"kind": "bch", "key": "fee", "owner": "alice", "sats": 20000, "vout": 1},
               {"kind": "genesis_parent", "key": "A", "owner": "alice", "sats": 50000},
           ],
           outputs=[
               {"owner": "bob", "sats": 1000, "genesis_from": 1, "token": FT(7)},
               {"owner": "alice", "sats": 68000},
           ]),
        _e("GEN-15", "genesis", "Spend token-bearing vout=0 also genesises a NEW category",
           "Existing token UTXO is vout=0 of its parent; spending it creates category=that parent txid "
           "AND must conserve the old category.",
           extra={"token_bearing_vout0": True},
           existing=[{"key": "old", "owner": "alice", "sats": 10000, "token": FT(50)}],
           inputs=[{"kind": "token", "key": "old", "owner": "alice"}],
           outputs=[
               {"owner": "bob", "sats": 1000, "token": {"category_from_existing": "old", "amount": 50, "nft": None}},
               {"owner": "alice", "sats": 8000, "genesis_from": 0, "token": NFT("none", "ff")},
           ]),
    ]

    # ── Cross-category genesis ───────────────────────────────────────────
    def xgen(n, title, desc, exist, outs, extra_in=None):
        ins = extra_in or []
        ins.append({"kind": "genesis_parent", "key": "A", "owner": "alice", "sats": 80000})
        for e in exist:
            ins.insert(0, {"kind": "token", "key": e["key"], "owner": "alice"})
        return _e(
            n, "cross-genesis", title, desc, existing=exist, inputs=ins, outputs=outs,
            dialects=["bip174-v0", "paytaca-145"],
        )

    c += [
        xgen("XGEN-01", "Genesis A + send FT B",
             "Create category A while transferring existing FT B.",
             [{"key": "B", "owner": "alice", "sats": 10000, "token": FT(1000)}],
             [
                 {"owner": "bob", "sats": 1000, "token": {"category_from_existing": "B", "amount": 1000, "nft": None}},
                 {"owner": "alice", "sats": 88000, "genesis_from": 1, "token": NFT("none", "aa")},
             ]),
        xgen("XGEN-02", "Genesis A + send NFT B",
             "Create category A while transferring an existing immutable NFT B.",
             [{"key": "B", "owner": "alice", "sats": 10000, "token": NFT("none", "beef")}],
             [
                 {"owner": "bob", "sats": 1000, "token": {"category_from_existing": "B", "amount": 0,
                                                          "nft": {"capability": "none", "commitment": "beef"}}},
                 {"owner": "alice", "sats": 88000, "genesis_from": 1, "token": FT(42)},
             ]),
        xgen("XGEN-03", "Genesis A + send hybrid B",
             "Create category A while transferring a hybrid NFT+FT of B.",
             [{"key": "B", "owner": "alice", "sats": 10000, "token": HYB("none", 77, "01")}],
             [
                 {"owner": "bob", "sats": 1000, "token": {"category_from_existing": "B", "amount": 77,
                                                          "nft": {"capability": "none", "commitment": "01"}}},
                 {"owner": "alice", "sats": 88000, "genesis_from": 1, "token": NFT("mutable", "")},
             ]),
        xgen("XGEN-04", "Genesis A + mint NFT B from baton",
             "Create category A while minting two NFTs of B from a minting baton.",
             [{"key": "B", "owner": "alice", "sats": 10000, "token": NFT("minting", "")}],
             [
                 {"owner": "alice", "sats": 1000, "token": {"category_from_existing": "B", "amount": 0,
                                                            "nft": {"capability": "minting", "commitment": ""}}},
                 {"owner": "bob", "sats": 1000, "token": {"category_from_existing": "B", "amount": 0,
                                                          "nft": {"capability": "none", "commitment": "m1"}}},
                 {"owner": "carol", "sats": 1000, "token": {"category_from_existing": "B", "amount": 0,
                                                            "nft": {"capability": "none", "commitment": "m2"}}},
                 {"owner": "alice", "sats": 86000, "genesis_from": 1, "token": NFT("none", "new")},
             ]),
        xgen("XGEN-05", "Genesis A + mutate NFT B",
             "Create category A while rewriting a mutable NFT of B.",
             [{"key": "B", "owner": "alice", "sats": 10000, "token": NFT("mutable", "old")}],
             [
                 {"owner": "bob", "sats": 1000, "token": {"category_from_existing": "B", "amount": 0,
                                                          "nft": {"capability": "mutable", "commitment": "new"}}},
                 {"owner": "alice", "sats": 88000, "genesis_from": 1, "token": FT(1)},
             ]),
        xgen("XGEN-06", "Genesis A + burn NFT B",
             "Create category A while omitting existing NFT B (implicit burn).",
             [{"key": "B", "owner": "alice", "sats": 10000, "token": NFT("none", "dead")}],
             [
                 {"owner": "alice", "sats": 89000, "genesis_from": 1, "token": NFT("none", "aa")},
             ]),
        xgen("XGEN-07", "Genesis A + send FT B + send NFT C",
             "Create category A while transferring FT B and NFT C in the same transaction.",
             [
                 {"key": "B", "owner": "alice", "sats": 8000, "token": FT(10)},
                 {"key": "C", "owner": "alice", "sats": 8000, "token": NFT("none", "cc")},
             ],
             [
                 {"owner": "bob", "sats": 1000, "token": {"category_from_existing": "B", "amount": 10, "nft": None}},
                 {"owner": "carol", "sats": 1000, "token": {"category_from_existing": "C", "amount": 0,
                                                            "nft": {"capability": "none", "commitment": "cc"}}},
                 {"owner": "alice", "sats": 93000, "genesis_from": 2, "token": NFT("minting", "")},
             ]),
    ]

    # ── Post-genesis ─────────────────────────────────────────────────────
    c += [
        _e("POST-01", "post-genesis", "Mint one NFT, preserve baton",
           existing=[{"key": "B", "owner": "alice", "sats": 10000, "token": NFT("minting", "")}],
           inputs=[{"kind": "token", "key": "B", "owner": "alice"}],
           outputs=[
               {"owner": "alice", "sats": 1000, "token": {"category_from_existing": "B", "amount": 0,
                                                          "nft": {"capability": "minting", "commitment": ""}}},
               {"owner": "bob", "sats": 8000, "token": {"category_from_existing": "B", "amount": 0,
                                                        "nft": {"capability": "none", "commitment": "n1"}}},
           ],
           dialects=["bip174-v0", "paytaca-145"]),
        _e("POST-02", "post-genesis", "Multi-mint three NFTs, preserve baton",
           existing=[{"key": "B", "owner": "alice", "sats": 20000, "token": NFT("minting", "")}],
           inputs=[{"kind": "token", "key": "B", "owner": "alice"}],
           outputs=[
               {"owner": "alice", "sats": 1000, "token": {"category_from_existing": "B", "amount": 0,
                                                          "nft": {"capability": "minting", "commitment": ""}}},
               {"owner": "bob", "sats": 1000, "token": {"category_from_existing": "B", "amount": 0,
                                                        "nft": {"capability": "none", "commitment": "01"}}},
               {"owner": "carol", "sats": 1000, "token": {"category_from_existing": "B", "amount": 0,
                                                          "nft": {"capability": "mutable", "commitment": "02"}}},
               {"owner": "dave", "sats": 1000, "token": {"category_from_existing": "B", "amount": 0,
                                                         "nft": {"capability": "none", "commitment": "03"}}},
           ]),
        _e("POST-03", "post-genesis", "Mint + downgrade baton to mutable",
           existing=[{"key": "B", "owner": "alice", "sats": 10000, "token": NFT("minting", "")}],
           inputs=[{"kind": "token", "key": "B", "owner": "alice"}],
           outputs=[
               {"owner": "alice", "sats": 1000, "token": {"category_from_existing": "B", "amount": 0,
                                                          "nft": {"capability": "mutable", "commitment": "baton"}}},
               {"owner": "bob", "sats": 8000, "token": {"category_from_existing": "B", "amount": 0,
                                                        "nft": {"capability": "none", "commitment": "n1"}}},
           ]),
        _e("POST-04", "post-genesis", "Mint + burn baton",
           existing=[{"key": "B", "owner": "alice", "sats": 10000, "token": NFT("minting", "")}],
           inputs=[{"kind": "token", "key": "B", "owner": "alice"}],
           outputs=[{"owner": "bob", "sats": 9000, "token": {"category_from_existing": "B", "amount": 0,
                                                             "nft": {"capability": "none", "commitment": "last"}}}]),
        _e("POST-05", "post-genesis", "Mutable preserve commitment",
           existing=[{"key": "B", "owner": "alice", "sats": 10000, "token": NFT("mutable", "same")}],
           inputs=[{"kind": "token", "key": "B", "owner": "alice"}],
           outputs=[{"owner": "bob", "sats": 9000, "token": {"category_from_existing": "B", "amount": 0,
                                                             "nft": {"capability": "mutable", "commitment": "same"}}}]),
        _e("POST-06", "post-genesis", "Mutable commitment rewrite",
           existing=[{"key": "B", "owner": "alice", "sats": 10000, "token": NFT("mutable", "old")}],
           inputs=[{"kind": "token", "key": "B", "owner": "alice"}],
           outputs=[{"owner": "bob", "sats": 9000, "token": {"category_from_existing": "B", "amount": 0,
                                                             "nft": {"capability": "mutable", "commitment": "new"}}}]),
        _e("POST-07", "post-genesis", "Mutable downgrade to immutable",
           existing=[{"key": "B", "owner": "alice", "sats": 10000, "token": NFT("mutable", "old")}],
           inputs=[{"kind": "token", "key": "B", "owner": "alice"}],
           outputs=[{"owner": "bob", "sats": 9000, "token": {"category_from_existing": "B", "amount": 0,
                                                             "nft": {"capability": "none", "commitment": "frozen"}}}]),
        _e("POST-08", "post-genesis", "Immutable transfer",
           existing=[{"key": "B", "owner": "alice", "sats": 10000, "token": NFT("none", "id")}],
           inputs=[{"kind": "token", "key": "B", "owner": "alice"}],
           outputs=[{"owner": "bob", "sats": 9000, "token": {"category_from_existing": "B", "amount": 0,
                                                             "nft": {"capability": "none", "commitment": "id"}}}],
           dialects=["bip174-v0", "paytaca-145"], sign_states=["unsigned", "signed"]),
        _e("POST-09", "post-genesis", "Immutable burn (omit NFT)",
           existing=[{"key": "B", "owner": "alice", "sats": 10000, "token": NFT("none", "id")}],
           inputs=[{"kind": "token", "key": "B", "owner": "alice"}],
           outputs=[{"owner": "alice", "sats": 9000}]),
        _e("POST-10", "post-genesis", "FT split",
           existing=[{"key": "B", "owner": "alice", "sats": 20000, "token": FT(100)}],
           inputs=[{"kind": "token", "key": "B", "owner": "alice"}],
           outputs=[
               {"owner": "bob", "sats": 1000, "token": {"category_from_existing": "B", "amount": 40, "nft": None}},
               {"owner": "alice", "sats": 18000, "token": {"category_from_existing": "B", "amount": 60, "nft": None}},
           ]),
        _e("POST-11", "post-genesis", "FT merge",
           existing=[
               {"key": "B", "owner": "alice", "sats": 8000, "token": FT(40), "category_group": "B"},
               {"key": "B2", "owner": "alice", "sats": 8000, "token": FT(60), "category_group": "B"},
           ],
           inputs=[
               {"kind": "token", "key": "B", "owner": "alice"},
               {"kind": "token", "key": "B2", "owner": "alice"},
           ],
           outputs=[{"owner": "bob", "sats": 14000, "token": {"category_from_existing": "B", "amount": 100, "nft": None}}]),
        _e("POST-12", "post-genesis", "FT partial burn",
           existing=[{"key": "B", "owner": "alice", "sats": 10000, "token": FT(100)}],
           inputs=[{"kind": "token", "key": "B", "owner": "alice"}],
           outputs=[{"owner": "bob", "sats": 9000, "token": {"category_from_existing": "B", "amount": 1, "nft": None}}]),
        _e("POST-13", "post-genesis", "Hybrid split FT keep NFT",
           existing=[{"key": "B", "owner": "alice", "sats": 20000, "token": HYB("none", 100, "id")}],
           inputs=[{"kind": "token", "key": "B", "owner": "alice"}],
           outputs=[
               {"owner": "bob", "sats": 1000, "token": {"category_from_existing": "B", "amount": 0,
                                                        "nft": {"capability": "none", "commitment": "id"}}},
               {"owner": "carol", "sats": 1000, "token": {"category_from_existing": "B", "amount": 100, "nft": None}},
           ]),
        _e("POST-14", "post-genesis", "Hybrid merge NFT+FT onto one output",
           existing=[
               {"key": "B", "owner": "alice", "sats": 8000, "token": NFT("none", "id"), "category_group": "B"},
               {"key": "B2", "owner": "alice", "sats": 8000, "token": FT(5), "category_group": "B"},
           ],
           inputs=[
               {"kind": "token", "key": "B", "owner": "alice"},
               {"kind": "token", "key": "B2", "owner": "alice"},
           ],
           outputs=[{"owner": "bob", "sats": 14000, "token": {"category_from_existing": "B", "amount": 5,
                                                              "nft": {"capability": "none", "commitment": "id"}}}]),
        _e("POST-15", "post-genesis", "Hybrid burn FT keep NFT",
           existing=[{"key": "B", "owner": "alice", "sats": 10000, "token": HYB("none", 50, "id")}],
           inputs=[{"kind": "token", "key": "B", "owner": "alice"}],
           outputs=[{"owner": "bob", "sats": 9000, "token": {"category_from_existing": "B", "amount": 0,
                                                             "nft": {"capability": "none", "commitment": "id"}}}]),
        _e("POST-16", "post-genesis", "Hybrid burn NFT keep FT",
           existing=[{"key": "B", "owner": "alice", "sats": 10000, "token": HYB("none", 50, "id")}],
           inputs=[{"kind": "token", "key": "B", "owner": "alice"}],
           outputs=[{"owner": "bob", "sats": 9000, "token": {"category_from_existing": "B", "amount": 50, "nft": None}}]),
    ]

    # ── Negative consensus ───────────────────────────────────────────────
    c += [
        _e("NEG-01", "negative", "Cloned immutable NFT",
           "Two immutable outputs from one immutable input.",
           expected_consensus="invalid", invalid_code="immutable_unmatched",
           existing=[{"key": "B", "owner": "alice", "sats": 10000, "token": NFT("none", "id")}],
           inputs=[{"kind": "token", "key": "B", "owner": "alice"}],
           outputs=[
               {"owner": "bob", "sats": 1000, "token": {"category_from_existing": "B", "amount": 0,
                                                        "nft": {"capability": "none", "commitment": "id"}}},
               {"owner": "carol", "sats": 1000, "token": {"category_from_existing": "B", "amount": 0,
                                                          "nft": {"capability": "none", "commitment": "id"}}},
           ]),
        _e("NEG-02", "negative", "Two successors from one mutable NFT",
           expected_consensus="invalid", invalid_code="mutable_overspend",
           existing=[{"key": "B", "owner": "alice", "sats": 10000, "token": NFT("mutable", "x")}],
           inputs=[{"kind": "token", "key": "B", "owner": "alice"}],
           outputs=[
               {"owner": "bob", "sats": 1000, "token": {"category_from_existing": "B", "amount": 0,
                                                        "nft": {"capability": "mutable", "commitment": "a"}}},
               {"owner": "carol", "sats": 1000, "token": {"category_from_existing": "B", "amount": 0,
                                                          "nft": {"capability": "mutable", "commitment": "b"}}},
           ]),
        _e("NEG-03", "negative", "Mutable upgraded to minting",
           expected_consensus="invalid", invalid_code="unsubstantiated_minting",
           existing=[{"key": "B", "owner": "alice", "sats": 10000, "token": NFT("mutable", "x")}],
           inputs=[{"kind": "token", "key": "B", "owner": "alice"}],
           outputs=[{"owner": "bob", "sats": 9000, "token": {"category_from_existing": "B", "amount": 0,
                                                             "nft": {"capability": "minting", "commitment": "x"}}}]),
        _e("NEG-04", "negative", "FT overspend",
           expected_consensus="invalid", invalid_code="ft_overspend",
           existing=[{"key": "B", "owner": "alice", "sats": 10000, "token": FT(10)}],
           inputs=[{"kind": "token", "key": "B", "owner": "alice"}],
           outputs=[{"owner": "bob", "sats": 9000, "token": {"category_from_existing": "B", "amount": 11, "nft": None}}]),
        _e("NEG-05", "negative", "FT without genesis (wrong category)",
           expected_consensus="invalid", invalid_code="ft_without_genesis",
           inputs=[{"kind": "bch", "key": "x", "owner": "alice", "sats": 10000, "vout": 1}],
           outputs=[{"owner": "bob", "sats": 8000,
                     "token": {"category": "00" * 32, "amount": 1, "nft": None}}]),
        _e("NEG-06", "negative", "Immutable commitment changed",
           expected_consensus="invalid", invalid_code="immutable_unmatched",
           existing=[{"key": "B", "owner": "alice", "sats": 10000, "token": NFT("none", "aa")}],
           inputs=[{"kind": "token", "key": "B", "owner": "alice"}],
           outputs=[{"owner": "bob", "sats": 9000, "token": {"category_from_existing": "B", "amount": 0,
                                                             "nft": {"capability": "none", "commitment": "bb"}}}]),
        _e("NEG-07", "negative", "41-byte commitment (Upgrade 9 consensus invalid)",
           expected_consensus="invalid", invalid_code="commitment_too_long",
           inputs=[{"kind": "genesis_parent", "key": "A", "owner": "alice", "sats": 10000}],
           outputs=[{"owner": "bob", "sats": 8000, "genesis_from": 0, "token": NFT("none", "cc" * 41)}],
           justification="CHIP v2.2.2 commitment_length limited to 40. BCHN Upgrade 12 (May 2026) raises to 128 — documented discrepancy."),
        _e("NEG-08", "negative", "Capability 3 (reserved)",
           expected_consensus="invalid", expected_psbt="valid", invalid_code="invalid_capability",
           inputs=[{"kind": "genesis_parent", "key": "A", "owner": "alice", "sats": 10000}],
           outputs=[{"owner": "bob", "sats": 8000, "inject": "cap3"}]),
        _e("NEG-09", "negative", "HAS_AMOUNT with amount 0",
           expected_consensus="invalid", expected_psbt="valid", invalid_code="zero_amount",
           inputs=[{"kind": "genesis_parent", "key": "A", "owner": "alice", "sats": 10000}],
           outputs=[{"owner": "bob", "sats": 8000, "inject": "amount0"}]),
        _e("NEG-10", "negative", "Empty token prefix (no NFT, no amount)",
           expected_consensus="invalid", expected_psbt="valid", invalid_code="no_tokens",
           inputs=[{"kind": "genesis_parent", "key": "A", "owner": "alice", "sats": 10000}],
           outputs=[{"owner": "bob", "sats": 8000, "inject": "empty_prefix"}]),
        _e("NEG-11", "negative", "Reserved bit 0x80 set",
           expected_consensus="invalid", expected_psbt="valid", invalid_code="reserved_bit",
           inputs=[{"kind": "genesis_parent", "key": "A", "owner": "alice", "sats": 10000}],
           outputs=[{"owner": "bob", "sats": 8000, "inject": "reserved"}]),
        _e("NEG-12", "negative", "Non-minimal CompactSize amount",
           expected_consensus="invalid", expected_psbt="valid", invalid_code="nonminimal_amount",
           inputs=[{"kind": "genesis_parent", "key": "A", "owner": "alice", "sats": 10000}],
           outputs=[{"owner": "bob", "sats": 8000, "inject": "nonminimal_amount"}]),
        _e("NEG-13", "negative", "FT amount > 2^63-1",
           expected_consensus="invalid", expected_psbt="valid", invalid_code="excessive_amount",
           inputs=[{"kind": "genesis_parent", "key": "A", "owner": "alice", "sats": 10000}],
           outputs=[{"owner": "bob", "sats": 8000, "inject": "amount_max_plus"}]),
        _e("NEG-14", "negative", "Commitment length 0 with HAS_COMMITMENT_LENGTH",
           expected_consensus="invalid", expected_psbt="valid", invalid_code="commitment_length_zero",
           inputs=[{"kind": "genesis_parent", "key": "A", "owner": "alice", "sats": 10000}],
           outputs=[{"owner": "bob", "sats": 8000, "inject": "commit_len0"}]),
        _e("NEG-15", "negative", "HAS_COMMITMENT_LENGTH without NFT",
           expected_consensus="invalid", expected_psbt="valid", invalid_code="commitment_without_nft",
           inputs=[{"kind": "genesis_parent", "key": "A", "owner": "alice", "sats": 10000}],
           outputs=[{"owner": "bob", "sats": 8000, "inject": "commit_no_nft"}]),
        _e("NEG-16", "negative", "Minting NFT of a category with no baton and no genesis",
           expected_consensus="invalid", invalid_code="unsubstantiated_minting",
           existing=[{"key": "B", "owner": "alice", "sats": 10000, "token": NFT("none", "x")}],
           inputs=[{"kind": "token", "key": "B", "owner": "alice"}],
           outputs=[{"owner": "bob", "sats": 9000, "token": {"category_from_existing": "B", "amount": 0,
                                                             "nft": {"capability": "minting", "commitment": "x"}}}]),
    ]

    # ── Encoding CHIP vectors (prefix only, wrapped in a genesis tx) ─────
    c += [
        _e("ENC-01", "encoding", "CHIP valid: 1 FT",
           "Official prefix vector no-NFT 1 FT.",
           inputs=[{"kind": "genesis_parent", "key": "A", "owner": "alice", "sats": 10000}],
           outputs=[{"owner": "bob", "sats": 8000, "genesis_from": 0, "token": FT(1)}],
           justification="CHIP token-prefix-valid.json / libauth token-prefix-valid.json"),
        _e("ENC-02", "encoding", "CHIP valid: 0-byte immutable + 1 FT hybrid",
           inputs=[{"kind": "genesis_parent", "key": "A", "owner": "alice", "sats": 10000}],
           outputs=[{"owner": "bob", "sats": 8000, "genesis_from": 0, "token": HYB("none", 1, "")}]),
        _e("ENC-03", "encoding", "CHIP valid: 1-byte immutable NFT",
           inputs=[{"kind": "genesis_parent", "key": "A", "owner": "alice", "sats": 10000}],
           outputs=[{"owner": "bob", "sats": 8000, "genesis_from": 0, "token": NFT("none", "cc")}]),
        _e("ENC-04", "encoding", "Wrong category endianness in display vs wire",
           "Generator emits UI-order category; prefix must reverse. This vector records both.",
           inputs=[{"kind": "genesis_parent", "key": "A", "owner": "alice", "sats": 10000}],
           outputs=[{"owner": "bob", "sats": 8000, "genesis_from": 0, "token": FT(1)}],
           extra={"record_endianness": True}),
           # record_endianness: generator writes category_ui + category_wire on the vector.
    ]

    # ── PSBT layer ───────────────────────────────────────────────────────
    c += [
        _e("PSBT-01", "psbt", "BIP-174 v0 unsigned with NON_WITNESS_UTXO",
           "Standard envelope SeedCash can parse.",
           inputs=[{"kind": "genesis_parent", "key": "A", "owner": "alice", "sats": 100000}],
           outputs=[{"owner": "bob", "sats": 98000, "genesis_from": 0, "token": NFT("none", "01")}],
           dialects=["bip174-v0"], sign_states=["unsigned"]),
        _e("PSBT-02", "psbt", "Paytaca v145 hybrid with 0x36",
           "GLOBAL_VERSION=145 uint32 LE; unsigned tx + v2 counts; PSBT_OUT_CASHTOKEN.",
           inputs=[{"kind": "genesis_parent", "key": "A", "owner": "alice", "sats": 100000}],
           outputs=[{"owner": "bob", "sats": 98000, "genesis_from": 0, "token": FT(9)}],
           dialects=["paytaca-145"], sign_states=["unsigned"],
           justification="paytaca-app/src/lib/multisig/psbt.js setPsbtVersion(145), PSBT_OUT_CASHTOKEN=0x36"),
        _e("PSBT-03", "psbt", "BIP-370 v2 (no unsigned tx)",
           "SeedCash currently rejects (requires GLOBAL unsigned tx).",
           expected_psbt="valid",
           extra={"seedcash_expected": "reject-no-unsigned-tx"},
           inputs=[{"kind": "genesis_parent", "key": "A", "owner": "alice", "sats": 100000}],
           outputs=[{"owner": "bob", "sats": 98000, "genesis_from": 0, "token": NFT("none", "")}],
           dialects=["bip370-v2"]),
        _e("PSBT-04", "psbt", "BCHN dialect: input 0x00 is CTxOut not prev tx",
           "Documented discrepancy vs BIP-174. SeedCash expects full prev tx.",
           extra={"seedcash_expected": "misparse-or-reject"},
           inputs=[{"kind": "genesis_parent", "key": "A", "owner": "alice", "sats": 100000}],
           outputs=[{"owner": "bob", "sats": 98000, "genesis_from": 0, "token": FT(3)}],
           dialects=["bchn-v0"],
           justification="BCHN src/psbt.h PSBT_IN_UTXO is a single CTxOut"),
        _e("PSBT-05", "psbt", "Missing NON_WITNESS_UTXO",
           expected_psbt="invalid", invalid_code="missing_non_witness_utxo",
           extra={"omit_utxo": True},
           inputs=[{"kind": "genesis_parent", "key": "A", "owner": "alice", "sats": 100000}],
           outputs=[{"owner": "bob", "sats": 98000, "genesis_from": 0, "token": NFT("none", "01")}]),
        _e("PSBT-06", "psbt", "Inconsistent 0x36 vs unsigned tx token",
           "Unsigned tx has FT 5; Paytaca 0x36 claims FT 999. Consensus from unsigned tx. Security failure if UI trusts 0x36.",
           expected_psbt="invalid", invalid_code="inconsistent_token_field",
           extra={"tamper_0x36_amount": 999},
           inputs=[{"kind": "genesis_parent", "key": "A", "owner": "alice", "sats": 100000}],
           outputs=[{"owner": "bob", "sats": 98000, "genesis_from": 0, "token": FT(5)}],
           dialects=["paytaca-145"]),
        _e("PSBT-07", "psbt", "Duplicate global unsigned-tx key",
           expected_psbt="invalid", invalid_code="duplicate_key",
           extra={"duplicate_unsigned": True},
           inputs=[{"kind": "genesis_parent", "key": "A", "owner": "alice", "sats": 10000}],
           outputs=[{"owner": "bob", "sats": 8000, "genesis_from": 0, "token": FT(1)}]),
        _e("PSBT-08", "psbt", "Truncated PSBT",
           expected_psbt="invalid", invalid_code="truncated_map",
           extra={"truncate": True},
           inputs=[{"kind": "genesis_parent", "key": "A", "owner": "alice", "sats": 10000}],
           outputs=[{"owner": "bob", "sats": 8000, "genesis_from": 0, "token": FT(1)}]),
        _e("PSBT-09", "psbt", "Wrong magic",
           expected_psbt="invalid", invalid_code="magic",
           extra={"bad_magic": True},
           inputs=[{"kind": "genesis_parent", "key": "A", "owner": "alice", "sats": 10000}],
           outputs=[{"owner": "bob", "sats": 8000}]),
        _e("PSBT-10", "psbt", "Partially signed (one of two inputs)",
           existing=[{"key": "B", "owner": "alice", "sats": 10000, "token": FT(10)}],
           inputs=[
               {"kind": "token", "key": "B", "owner": "alice"},
               {"kind": "bch", "key": "fee", "owner": "alice", "sats": 20000, "vout": 1},
           ],
           outputs=[{"owner": "bob", "sats": 25000, "token": {"category_from_existing": "B", "amount": 10, "nft": None}}],
           sign_states=["partial"], dialects=["bip174-v0"]),
    ]

    # ── Sighash ──────────────────────────────────────────────────────────
    for i, (sid, name, sh) in enumerate([
        ("SIG-01", "ALL|FORKID", "ALL|FORKID"),
        ("SIG-02", "NONE|FORKID", "NONE|FORKID"),
        ("SIG-03", "SINGLE|FORKID", "SINGLE|FORKID"),
        ("SIG-04", "ALL|ANYONECANPAY|FORKID", "ALL|ANYONECANPAY|FORKID"),
        ("SIG-05", "ALL|FORKID|UTXOS", "ALL|FORKID|UTXOS"),
    ], 1):
        c.append(_e(sid, "sighash", f"Sign {name}",
                    f"P2PKH genesis NFT signed with {name}.",
                    inputs=[{"kind": "genesis_parent", "key": "A", "owner": "alice", "sats": 100000}],
                    outputs=[{"owner": "bob", "sats": 98000, "genesis_from": 0, "token": NFT("none", "s1")}],
                    sighash=sh, sign_states=["signed"], dialects=["bip174-v0"],
                    justification="CHIP signing serialization + SIGHASH_UTXOS section"))
    c.append(_e("SIG-06", "sighash", "UTXOS+ANYONECANPAY is CHIP-invalid",
                "VM evaluation must fail. Signing this combination is refused by the laboratory.",
                expected_consensus="valid", expected_psbt="valid", invalid_code="utxos_with_anyonecanpay",
                extra={"force_sighash": True},
                inputs=[{"kind": "genesis_parent", "key": "A", "owner": "alice", "sats": 100000}],
                outputs=[{"owner": "bob", "sats": 98000, "genesis_from": 0, "token": FT(1)}],
                sighash="ALL|FORKID", sign_states=["signed"]))

    # ── Scripts ──────────────────────────────────────────────────────────
    for sid, st, title in [
        ("SCR-01", "p2pkh", "Token-aware P2PKH locking bytecode (still 76a914..88ac)"),
        ("SCR-02", "p2sh20", "P2SH20"),
        ("SCR-03", "p2sh32", "P2SH32"),
        ("SCR-04", "bare", "Bare P2PK"),
    ]:
        c.append(_e(sid, "script", title,
                    "Locking bytecode type; token prefix is prepended. CashAddr type bits are not on-chain.",
                    inputs=[{"kind": "genesis_parent", "key": "A", "owner": "alice", "sats": 100000}],
                    outputs=[{"owner": "bob", "sats": 98000, "genesis_from": 0, "token": NFT("none", "sc"),
                              "script": st}],
                    script_type=st))
    c.append(_e("SCR-05", "script", "OP_RETURN before P2PKH (WYSIWYS trap)",
                "Output 0 is OP_RETURN; output 1 is payment. SeedCash SC-02 pairs addresses by filtered list vs raw index.",
                extra={"seedcash_expected": "wysiwys-mismatch"},
                inputs=[{"kind": "genesis_parent", "key": "A", "owner": "alice", "sats": 100000}],
                outputs=[
                    {"owner": "bob", "sats": 0, "script": "op_return"},
                    {"owner": "bob", "sats": 98000, "genesis_from": 0, "token": NFT("none", "or")},
                ]))

    # ── BCMR (metadata, not consensus) ───────────────────────────────────
    c.append(_e("BCMR-01", "metadata", "OP_RETURN BCMR-looking payload + token genesis",
                "BCMR is not consensus. Signer must not treat OP_RETURN as token metadata authority.",
                extra={"bcmr_metadata_only": True},
                inputs=[{"kind": "genesis_parent", "key": "A", "owner": "alice", "sats": 100000}],
                outputs=[
                    {"owner": "bob", "sats": 0, "script": "op_return"},
                    {"owner": "alice", "sats": 98000, "genesis_from": 0, "token": HYB("minting", 100, "")},
                ]))

    # ── vout=0 is NOT automatically genesis ──────────────────────────────
    c += [
        _e("VOUT0-NO-GENESIS", "genesis",
           "Spend token UTXO at vout=1; dummy BCH occupies parent vout=0",
           "prev_index==1 so this spend MUST NOT create a category. Contrast GEN-01 (prev_index==0).",
           existing=[{"key": "B", "owner": "alice", "sats": 10000, "token": FT(50)}],
           inputs=[{"kind": "token", "key": "B", "owner": "alice"}],
           outputs=[{"owner": "bob", "sats": 9000, "token": {"category_from_existing": "B", "amount": 50, "nft": None}}],
           dialects=["bip174-v0", "paytaca-145"],
           extra={"assert_genesis_empty": True}),
        _e("VOUT0-MIXED", "genesis",
           "Same tx: genesis via vin spending vout=0 AND transfer of existing token at vout=1",
           existing=[{"key": "B", "owner": "alice", "sats": 10000, "token": NFT("none", "keep")}],
           inputs=[
               {"kind": "genesis_parent", "key": "A", "owner": "alice", "sats": 80000},
               {"kind": "token", "key": "B", "owner": "alice"},
           ],
           outputs=[
               {"owner": "bob", "sats": 1000, "genesis_from": 0, "token": FT(7)},
               {"owner": "carol", "sats": 8000, "token": {"category_from_existing": "B", "amount": 0,
                                                          "nft": {"capability": "none", "commitment": "keep"}}},
               {"owner": "alice", "sats": 78000},
           ],
           dialects=["bip174-v0", "paytaca-145"]),
        _e("BCH-VOUT1", "genesis",
           "BCH-only spend of parent vout=1 (dummy at vout=0). No tokens, no genesis.",
           inputs=[{"kind": "bch", "key": "X", "owner": "alice", "sats": 50000, "vout": 1}],
           outputs=[{"owner": "bob", "sats": 48000}],
           dialects=["bip174-v0", "paytaca-145"],
           extra={"assert_genesis_empty": True}),
    ]

    # ── Same category FT + NFT on separate outputs ───────────────────────
    c += [
        _e("SAMECAT-01", "hybrid",
           "Minting baton: FT and NFT of same category on two outputs",
           existing=[{"key": "B", "owner": "alice", "sats": 20000, "token": HYB("minting", 100, "")}],
           inputs=[{"kind": "token", "key": "B", "owner": "alice"}],
           outputs=[
               {"owner": "alice", "sats": 1000, "token": {"category_from_existing": "B", "amount": 0,
                                                          "nft": {"capability": "minting", "commitment": ""}}},
               {"owner": "bob", "sats": 1000, "token": {"category_from_existing": "B", "amount": 40, "nft": None}},
               {"owner": "carol", "sats": 1000, "token": {"category_from_existing": "B", "amount": 0,
                                                          "nft": {"capability": "none", "commitment": "n1"}}},
               {"owner": "alice", "sats": 16000, "token": {"category_from_existing": "B", "amount": 60, "nft": None}},
           ],
           dialects=["bip174-v0", "paytaca-145"]),
        _e("BURN-MULTI", "post-genesis",
           "Burn FT of B and NFT of C in one tx; keep D",
           existing=[
               {"key": "B", "owner": "alice", "sats": 8000, "token": FT(1000)},
               {"key": "C", "owner": "alice", "sats": 8000, "token": NFT("none", "gone")},
               {"key": "D", "owner": "alice", "sats": 8000, "token": NFT("none", "keep")},
           ],
           inputs=[
               {"kind": "token", "key": "B", "owner": "alice"},
               {"kind": "token", "key": "C", "owner": "alice"},
               {"kind": "token", "key": "D", "owner": "alice"},
           ],
           outputs=[
               {"owner": "bob", "sats": 7000, "token": {"category_from_existing": "B", "amount": 700, "nft": None}},
               {"owner": "carol", "sats": 7000, "token": {"category_from_existing": "D", "amount": 0,
                                                          "nft": {"capability": "none", "commitment": "keep"}}},
           ],
           dialects=["bip174-v0", "paytaca-145"]),
    ]

    # ── Monster / DeFi-pattern transactions ──────────────────────────────
    c += [
        _e("MONSTER-01", "complex",
           "Genesis A + transfer mutable B (vout=1) + split hybrid C + FT burn D + NFT burn E + BCH vout1",
           existing=[
               {"key": "B", "owner": "alice", "sats": 8000, "token": NFT("mutable", "old")},
               {"key": "C", "owner": "alice", "sats": 8000, "token": HYB("none", 50, "cid")},
               {"key": "D", "owner": "alice", "sats": 8000, "token": FT(1000)},
               {"key": "E", "owner": "alice", "sats": 8000, "token": NFT("none", "burnme")},
           ],
           inputs=[
               {"kind": "genesis_parent", "key": "A", "owner": "alice", "sats": 90000},
               {"kind": "token", "key": "B", "owner": "alice"},
               {"kind": "token", "key": "C", "owner": "alice"},
               {"kind": "token", "key": "D", "owner": "alice"},
               {"kind": "token", "key": "E", "owner": "alice"},
               {"kind": "bch", "key": "X", "owner": "alice", "sats": 20000, "vout": 1},
           ],
           outputs=[
               {"owner": "bob", "sats": 2000, "genesis_from": 0, "token": HYB("minting", 10, "")},
               {"owner": "carol", "sats": 2000, "token": {"category_from_existing": "B", "amount": 0,
                                                          "nft": {"capability": "mutable", "commitment": "new"}}},
               {"owner": "dave", "sats": 2000, "token": {"category_from_existing": "C", "amount": 50, "nft": None}},
               {"owner": "alice", "sats": 2000, "token": {"category_from_existing": "C", "amount": 0,
                                                          "nft": {"capability": "none", "commitment": "cid"}}},
               {"owner": "bob", "sats": 2000, "token": {"category_from_existing": "D", "amount": 700, "nft": None}},
               {"owner": "alice", "sats": 100000},
           ],
           dialects=["bip174-v0", "paytaca-145"]),
        _e("MONSTER-02", "complex",
           "Two genesis categories + mint from existing baton + immutable transfer",
           existing=[
               {"key": "M", "owner": "alice", "sats": 10000, "token": NFT("minting", "")},
               {"key": "I", "owner": "alice", "sats": 10000, "token": NFT("none", "imm")},
           ],
           inputs=[
               {"kind": "genesis_parent", "key": "A", "owner": "alice", "sats": 40000},
               {"kind": "genesis_parent", "key": "B", "owner": "alice", "sats": 40000},
               {"kind": "token", "key": "M", "owner": "alice"},
               {"kind": "token", "key": "I", "owner": "alice"},
           ],
           outputs=[
               {"owner": "bob", "sats": 1000, "genesis_from": 0, "token": FT(1)},
               {"owner": "carol", "sats": 1000, "genesis_from": 1, "token": NFT("none", "g")},
               {"owner": "alice", "sats": 1000, "token": {"category_from_existing": "M", "amount": 0,
                                                          "nft": {"capability": "minting", "commitment": ""}}},
               {"owner": "dave", "sats": 1000, "token": {"category_from_existing": "M", "amount": 0,
                                                          "nft": {"capability": "none", "commitment": "m1"}}},
               {"owner": "bob", "sats": 1000, "token": {"category_from_existing": "I", "amount": 0,
                                                        "nft": {"capability": "none", "commitment": "imm"}}},
               {"owner": "alice", "sats": 70000},
           ],
           dialects=["bip174-v0", "paytaca-145"]),
        _e("MONSTER-03", "complex",
           "DeFi-like: swap-shaped FT A vs FT B, leftover change, dust BCH",
           existing=[
               {"key": "A", "owner": "alice", "sats": 10000, "token": FT(500)},
               {"key": "B", "owner": "bob", "sats": 10000, "token": FT(80)},
           ],
           inputs=[
               {"kind": "token", "key": "A", "owner": "alice"},
               {"kind": "token", "key": "B", "owner": "bob"},
           ],
           outputs=[
               {"owner": "alice", "sats": 9000, "token": {"category_from_existing": "B", "amount": 80, "nft": None}},
               {"owner": "bob", "sats": 9000, "token": {"category_from_existing": "A", "amount": 500, "nft": None}},
           ],
           dialects=["bip174-v0", "paytaca-145"]),
        _e("MONSTER-04", "complex",
           "LP-like: two FT in, hybrid NFT position out + leftover FT, burn some A",
           existing=[
               {"key": "A", "owner": "alice", "sats": 10000, "token": FT(100)},
               {"key": "B", "owner": "alice", "sats": 10000, "token": FT(200)},
               {"key": "P", "owner": "alice", "sats": 10000, "token": NFT("minting", "lp")},
           ],
           inputs=[
               {"kind": "token", "key": "A", "owner": "alice"},
               {"kind": "token", "key": "B", "owner": "alice"},
               {"kind": "token", "key": "P", "owner": "alice"},
           ],
           outputs=[
               {"owner": "alice", "sats": 1000, "token": {"category_from_existing": "A", "amount": 40, "nft": None}},
               {"owner": "alice", "sats": 1000, "token": {"category_from_existing": "B", "amount": 200, "nft": None}},
               {"owner": "alice", "sats": 1000, "token": {"category_from_existing": "P", "amount": 0,
                                                          "nft": {"capability": "minting", "commitment": "lp"}}},
               {"owner": "alice", "sats": 1000, "token": {"category_from_existing": "P", "amount": 0,
                                                          "nft": {"capability": "none", "commitment": "pos1"}}},
               {"owner": "alice", "sats": 25000},
           ],
           dialects=["bip174-v0", "paytaca-145"]),
        _e("MONSTER-05", "complex",
           "Four categories: genesis hybrid + mint + mutable rewrite + FT split + BCH",
           existing=[
               {"key": "M", "owner": "alice", "sats": 8000, "token": NFT("minting", "")},
               {"key": "U", "owner": "alice", "sats": 8000, "token": NFT("mutable", "u0")},
               {"key": "F", "owner": "alice", "sats": 8000, "token": FT(9)},
           ],
           inputs=[
               {"kind": "genesis_parent", "key": "G", "owner": "alice", "sats": 50000},
               {"kind": "token", "key": "M", "owner": "alice"},
               {"kind": "token", "key": "U", "owner": "alice"},
               {"kind": "token", "key": "F", "owner": "alice"},
               {"kind": "bch", "key": "Z", "owner": "alice", "sats": 15000, "vout": 1},
           ],
           outputs=[
               {"owner": "bob", "sats": 1000, "genesis_from": 0, "token": HYB("none", 3, "g1")},
               {"owner": "alice", "sats": 1000, "token": {"category_from_existing": "M", "amount": 0,
                                                          "nft": {"capability": "minting", "commitment": ""}}},
               {"owner": "carol", "sats": 1000, "token": {"category_from_existing": "M", "amount": 0,
                                                          "nft": {"capability": "mutable", "commitment": "mnew"}}},
               {"owner": "dave", "sats": 1000, "token": {"category_from_existing": "U", "amount": 0,
                                                         "nft": {"capability": "none", "commitment": "frozen"}}},
               {"owner": "bob", "sats": 1000, "token": {"category_from_existing": "F", "amount": 4, "nft": None}},
               {"owner": "alice", "sats": 1000, "token": {"category_from_existing": "F", "amount": 5, "nft": None}},
               {"owner": "alice", "sats": 60000},
           ],
           dialects=["bip174-v0", "paytaca-145"]),
    ]

    return c
